name: Generate Changelog using Git Cliff
run-name: Generating CHANGELOG.MD
on: [push]
jobs:
  generate-changelog:
      name: Generate changelog
      runs-on: ubuntu-22.04
      outputs:
        release_body: ${{ steps.git-cliff.outputs.content }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Generate a changelog
          uses: orhun/git-cliff-action@v3
          with:
            config: cliff.toml
            args: --verbose
          env:
            OUTPUT: CHANGELOG.md
            GITHUB_REPO: ${{ github.repository }}
